In [ ]:
import torch
import pandas as pd

In [ ]:
!nvidia-smi

Wed Sep  3 08:44:55 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch as pd
import torch
import numpy as np
import matplotlib.pyplot as plt



print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating Tensor

Pytorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar

scalar =torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX =  torch.tensor([[7,8],
                        [9,10]])


MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why Random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensor full of random number  and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random number`

Torch Random Tensors = https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensors of size (3,4)


random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8789, 0.4897, 0.8423, 0.0349],
        [0.8768, 0.4458, 0.9670, 0.2543],
        [0.1085, 0.8638, 0.9926, 0.2506]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) # height, width, color channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all zeros
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like\


In [ ]:
# user torch.range()
torch.range(0, 10)

/tmp/ipython-input-4088743967.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# user torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# user torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1 )

In [ ]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating Tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)

In [ ]:
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor DataTypes

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorchh & Deep Learning:
1. Tensors not right dataype
2. Tensors not right shape
3. Tensor not on right device

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype= None, device = None, requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 8], dtype = torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

### Getting information from Sensors

1. Tensors not right dataype - to do get Datatype from a tensor, can use `tensor.dype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2186, 0.0019, 0.8002, 0.1573],
        [0.6724, 0.2846, 0.5555, 0.2172],
        [0.9669, 0.9122, 0.6049, 0.9953]])

In [ ]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device of Tensor: {some_tensor.device}")

tensor([[0.2186, 0.0019, 0.8002, 0.1573],
        [0.6724, 0.2846, 0.5555, 0.2172],
        [0.9669, 0.9122, 0.6049, 0.9953]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device of Tensor: cpu


### Manipulating Tensor (Tensor Operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (Element - wise)
4. Division
5. Matrix Multipication


In [ ]:
# Create tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication (dot product)


https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two rules that performing matrix multiplication neeeds to satisfy:
1. The **Inner Dimensions** Must Match:
*   `(3,2) @ (3,2)` Wont Work
*   `(2,3) @ (3,2)` Will Work
*   `(3,2) @ (2,3)` Will Work

2. The Resulting matrix has the shape of the **Outer Dimension**:
*   `(2,3) @ (3,2)` -> `(2,2)`
*   `(3,2) @ (2,3) ` -> `(3,3)`




In [ ]:
# Element Wise Muliplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multipication by hand
1 * 1 + 2* 2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 319 µs, sys: 59 µs, total: 378 µs
Wall time: 987 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 243 µs, sys: 45 µs, total: 288 µs
Wall time: 294 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

# Shape for matrix multiplication
tensor_B = torch.tensor([[7,10],
                         [8,4],
                         [9,6]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (its an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To Fix our tensor Shape issues, we can manipulate the shape of one of our tensor using a  **transpose**

A **Transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8,  4],
        [ 9,  6]])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10,  4,  6]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The Matrix Multiplication operation works when tensor_B is transposed
print(f"Original Shapes: Tensor_A = {tensor_A.shape}, Original Shapes: Tensor_B = {tensor_B.shape} ")

# The Matrix Multiplication operation works when tensor_B is transposed
print(f"New Shapes: Tensor_A = {tensor_A.shape} (Same with Above ), New Shapes: Tensor_B = {tensor_B.T.shape} ")

print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inher dimensions must match")

print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")

Original Shapes: Tensor_A = torch.Size([3, 2]), Original Shapes: Tensor_B = torch.Size([3, 2]) 
New Shapes: Tensor_A = torch.Size([3, 2]) (Same with Above ), New Shapes: Tensor_B = torch.Size([2, 3]) 
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inher dimensions must match
Output:

tensor([[27, 16, 21],
        [61, 40, 51],
        [95, 64, 81]])

Output Shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find the mean - note: the torch mean() function requires a tensor of float32 datype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
%%time
# find the sum
torch.sum(x), x.sum()

CPU times: user 648 µs, sys: 0 ns, total: 648 µs
Wall time: 580 µs


(tensor(460), tensor(460))

## Finding the positional min and Max

In [ ]:
# find the position in tensor that has min value with argmin() -> return index position of target tensor where the min value occurs
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors



*   Reshaping -> reshapes an input tensor to a defined shaped
*   View -> Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*   Stacking -> combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze -> remove all `1` dimension from a tensor
* Unsquezze -> add `1` dimension to a target tensor
* Permute -> Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:

# add an Extra Dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z change x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squezee() - remove all single dimension from a target tensor
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor {x_squeezed}")
print(f"New Shape {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New Tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape torch.Size([9])


In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() -> Adds a single dimension to a target tensor at specific dim (dimension)

print(f"Previous Target: {x_squeezed}")
print(f"New Shape {x_squeezed.shape}")

# add an extra dimension wtih unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim =0)
print(f"\nNew Tensor {x_unsqueezed}")
print(f"New Shhape {x_unsqueezed.shape}")


Previous Target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape torch.Size([9])

New Tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shhape torch.Size([1, 9])


In [ ]:
# torch.permute -> rearranges the dimensions of a target tensor in a specified order
x_original= torch.rand(size = (224,224,3)) #[Height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim)
x_permuted = x_original.permute(2,0,1) # Shifts axis 0->1, 1->2,2->0


print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [ ]:
x_permuted

tensor([[[0.9763, 0.8708, 0.3045,  ..., 0.0537, 0.0924, 0.3743],
         [0.7353, 0.0211, 0.0935,  ..., 0.2251, 0.1822, 0.2933],
         [0.9600, 0.1754, 0.5021,  ..., 0.0755, 0.8261, 0.9945],
         ...,
         [0.1110, 0.9932, 0.5552,  ..., 0.8075, 0.2931, 0.6043],
         [0.8528, 0.2645, 0.9006,  ..., 0.4154, 0.6533, 0.6683],
         [0.1223, 0.1829, 0.3072,  ..., 0.4856, 0.3113, 0.0502]],

        [[0.9908, 0.4535, 0.3602,  ..., 0.8912, 0.3097, 0.2720],
         [0.7253, 0.3225, 0.5584,  ..., 0.5567, 0.0077, 0.3344],
         [0.5874, 0.9466, 0.1895,  ..., 0.1151, 0.9068, 0.2552],
         ...,
         [0.8387, 0.9734, 0.9913,  ..., 0.2403, 0.5393, 0.9925],
         [0.6930, 0.6274, 0.8354,  ..., 0.9332, 0.4713, 0.1764],
         [0.5664, 0.2462, 0.9727,  ..., 0.5070, 0.4486, 0.9801]],

        [[0.0203, 0.6562, 0.8733,  ..., 0.2098, 0.3173, 0.7449],
         [0.4598, 0.6775, 0.0103,  ..., 0.4131, 0.2572, 0.0350],
         [0.5069, 0.2619, 0.4703,  ..., 0.0987, 0.0732, 0.

## Indexing (Selecting data from tensor)

Indexing with Pytorch is similar to indexing with Numpy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on middle bracket (last dim)
x[0][1][2]

tensor(6)

In [ ]:
# you can also use ":" to select ll of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0 dimension but only the 1 index values of 1st and 2nd

x[:,1,1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension\
x[0,0,:]

tensor([1, 2, 3])

## Pytorch tensors and NumPy

Numpy is a populer scientific Python numerical computing library

and because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> PyTroch, Pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array, What will this do to `tensor`?

array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?

tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducebility(Traying to take random out of random)

in short how a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again then again`

to reduce the randomness in neural networks and PyTorch comes the concept of a **Random Seet**

Essentially what the random seed does is "Flavour" the randomness

In [ ]:
import torch

# create two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)


print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.5430, 0.9163, 0.8994, 0.8866],
        [0.9615, 0.0721, 0.9407, 0.3016],
        [0.2928, 0.7100, 0.0534, 0.1471]])
tensor([[0.7629, 0.2831, 0.0918, 0.3678],
        [0.0850, 0.7045, 0.6580, 0.2754],
        [0.4175, 0.4242, 0.3989, 0.5366]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensor
import torch

#Set the random Seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
* https://docs.pytorch.org/docs/stable/notes/randomness.html

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPU = Faster Computetation on number

### Getting a GPU

1. Easisest - Use Google Colab for a free GPU
2. Use your own GPU - takes a little bit of setup
3. Use Cloud Computing


In [ ]:
!nvidia-smi

Wed Sep  3 08:45:30 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   48C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For Pytorch since it's capable of running compute on the GPU or CPU, its best practice to setup device agonist code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices


E.g run on GPU if avaiable, else default to CPU

In [ ]:
# Setup Device agnostic Code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensor (and models) on the GPU

The reason we want our tensor/models on the GPU is because using a GPU results in faster computations

In [ ]:


# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device ="cpu")

# tensorTensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu
CPU times: user 1.56 ms, sys: 38 µs, total: 1.6 ms
Wall time: 1.4 ms


In [ ]:
# Create a tensor (default on the CPU)
tensor_on_gpu = tensor.to(device)

# tensorTensor not on GPU
tensor_on_gpu

CPU times: user 194 µs, sys: 14 µs, total: 208 µs
Wall time: 160 µs


tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors to CPU

In [ ]:
# if tensors is on GPU, cant transfrom it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')